### ISSUE TITLE
★ [공지] 첫 번째 밋업 참가 신청 (2월 8일-목)

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CampusFest/5th#10]
2월 8일(목) D2 StartupFactory에서 첫 번째 밋업이 진행됩니다.
※ 첫 번째 밋업에 참여를 원하시는 분은 댓글 남겨주세요!

참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.
오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!

일시 : 2월 8일(목), 오후 2시 - 7시
장소 : 강남역 메리츠 타워 16층 D2 Startup Factory ([위치보기](https://map.naver.com/local/siteview.nhn?code=36797269))
★1층 오른쪽 출입구에서 16층 간다고 말해주시면 열어주실꺼에요!!★
* 오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
* 오후 5시 - 7시 : Tech Talk (w/ pizza party)

Tech Talk 발표를 원하시는 분들도 댓글로 알려주세요 :)
(*발표는 5~20분 정도로 희망자 수에 따라 시간은 조절될 수 있습니다.)

**Comment by JuhoKang** [comment]
@korsejong 과 밋업 참여합니다. 중간 '일시'항목 요일에 오타있는것 같습니다 (수 -> 목). 순간 흠칫했어요

**Comment by Kang-heesuk** [comment]
@JuhoKang 어머 감사해요, 저도 흠칫했네요 수정했습니당 :)

**Comment by kuj0210** [comment]
opensourceproject(김우진,이건희,고대석)팀 전원참가합니다!
(혹시 팀명 IoT-Pet-Home-System으로 변경가능할가요ㅜㅜ)

**Comment by Kang-heesuk** [comment]
@kuj0210 대회 제출이후 팀명 변경은 원칙적으로 불가하나 특별한 경우로 간주되어 변경진행하도록 하겠습니다. :)

이미 제작이 완료 (이름표 및 팀명 테이블 배너)된 물품에 대해서는 추가 제작이 어려운 점 양해 부탁드리고, 이후 예정된 제작 물품에 대해서는 수정해주신 팀명으로 반영 될 수 있도록 하겠습니다

**Comment by kuj0210** [comment]
감사합니다!

**Comment by so3500** [comment]
Nanum 팀 2명(이성온, 정구범) 밋업 참여합니다!

**Comment by xxxnell** [comment]
밋업 참여하겠습니다 😃

**Comment by oh3vci** [comment]
prefeel-lib 팀 3명(김대호 @oh3vci, 이우찬 @WoochanLee 허경영 @bbvch13531) 참여합니다.
김대호 팀원은 Tech Talk 시간에 맞춰 올 것 같습니다.

**Comment by ryuhangyeong** [comment]
daily-health-originer 밋업 참가합니다.

**Comment by rouismia** [comment]
LaunchPAD_JS 팀 (김시형 @rouismia) 참여합니다.

**Comment by grohong** [comment]
THStorytellingView.git 팀 3명 (홍창남, 한지웅, 홍성호) 참여합니다~!

**Comment by poirin** [comment]
MyDiary팀 2명(강병구, 김형민) 참가 신청합니다

**Comment by Kang-heesuk** [comment]
Tech talk에서 짧게 프로젝트를 운영하면서 궁금했던 점이나 나누고 싶은 이야기가 있으신 분들은 댓글로 남겨주세요!!

**Comment by oh3vci** [comment]
React를 활용해서 하는 프로젝트들이 많이 보이는데, 다들 프로젝트 구조를 어떻게 설계하는 지 궁금합니다.

**Comment by kuj0210** [comment]
IoT-Pet-Home-System(이전 opensourceproject) 팀입니다. 2월 8일 전원참석 예정이었는데 고대석 학우가 늦게 출발해야하는 상황이 있어서 1시간 가량 늦을 예정인데 가능한지 알고싶습니다!

프로젝트관련 설계에서 다들 문서를 어떤식으로 준비하시는지 알고 싶습니다. 
유스케이스 다이어그램, 클래스 다이어그램.... 등등 많은 설계관련 문서를 전부다 준비하시는지 아니면 간략하게(어떤식으로)만 하시는지 알고싶고 완성된 프로그램의 성능을 검증하는 방법이나 테스트할 때 필수적으로 보시는 부분이 있나 여쭤보고싶어요!

**Comment by ryuhangyeong** [comment]
@Kang-heesuk 나만의 재사용 가능한 컴포넌트 만들기에 대해서 간단히 발표하고 싶은데요. 10분정도도 가능한가요?

**Comment by grohong** [comment]
오픈소스 라이브러리를 만들때 구현범위와 확장성에 대해 고민이 많아서 이번 기회에 이야기 해보고 싶습니다~!
[나만의 라이브러리 만들기.pdf](https://github.com/D2CampusFest/5th/files/1706199/default.pdf)

**Comment by byeolbit** [comment]
Dr.Jekyll팀 두명(@byeolbit, @sh92)참가합니다

**Comment by Kang-heesuk** [comment]
@kuj0210 네네 늦게 도착하셔도 괜찮습니다! 편하게 개발하는 분위기니 도착하시는 대로 각자 진행하시면 됩니다. :)

**Comment by Kang-heesuk** [comment]
@ryuhangyeong 네네 그럼요 좋습니다 :) 발표자료가 있다면 미리 댓글로 부탁드릴께요! 혹은 발표 이후에 남겨주셔도 좋습니당

**Comment by hwonyo** [comment]
내일 밋업 참여하겠습니다!

**Comment by KimBoWoon** [comment]
등록이 늦었내요 죄송합니다. 
내일 밋업 참가합니다.

**Comment by ryuhangyeong** [comment]
@Kang-heesuk 부족하지만 열심히 해보겠습니다.
[발표자료](https://www.slideshare.net/hangyeongryu/ss-87384303)
