### ISSUE TITLE
[LaunchPAD_JS] IOS 환경에서의 Canvas 애니메이션 처리 문제

### ISSUE THREAD

**Issue by rouismia** [D2CampusFest/5th#12]
## 이슈

> IOS Canavas 비동기 애니메이션 처리 문제

## 문제점

> IOS 환경에서의 Canvas Animation 처리 시 안드로이드/PC 환경에서보다 매끄럽지 못함.
	Version1.0 IOS_2 Click▼
[![LPSJ_5](https://github.com/rouismia/LaunchPAD_JS/blob/V_1.0/img/IOS_2.gif?raw=true)](https://www.youtube.com/watch?v=HLqTAC-xV54 "LPSJ_4")
	Version1.0 Android Click▼
[![LPSJ_6](https://github.com/rouismia/LaunchPAD_JS/blob/V_1.0/img/Android.gif?raw=true)](https://www.youtube.com/watch?v=3_J87RzH0CA "LPSJ_4")
> 하나의 애니메이션만 실행 시 매끄럽게 동작하지만, 여러 애니메이션이 동시에 실행되면 버벅이는 것을 확인할 수 있음.

## 원인

> IOS 기기의 성능 문제로 애니메이션이 끊어지는 것이면 좋겠으나, IOS 환경을 고려했을 때 단순히 성능 문제 뿐만이 아닌, Javascript 비동기 처리에 문제가 있는 것으로 예상이 됩니다. 이를 위한 코드 최적화가 필요하다고 생각이 됩니다.

## 희망사항

> 비동기 애니메이션 최적화를 위한 방법에 대한 가르침을 주셨으면 좋겠습니다.

**Comment by JuhoKang** [comment]
도움이 될것같은 블로그 포스트 링크 입니다. 이미 보셨을지도 모르지만...
저희 프로젝트도 canvas위에 포현을 버벅임 없이 매끄럽게 하는게 중요해서 고민 많이 하고있네요.
http://cubiq.org/performance-tricks-for-mobile-web-development

**Comment by rouismia** [comment]
@JuhoKang 의견 감사합니다. 저는 실시간 랜더링을 위해 timer나 interval을 사용하지 않고, requestAnimationFrame을 이용한 animate를 사용하였습니다. timer나 interval을 사용하면 별개의 스레드를 소모하여 엄청나게 버벅이는 현상이 발생하였습니다. 그럼에도 불구하고 제가 가진 ipad에서는 버벅임이 발생하게 됐습니다. 제 기기가 구형이라 성능 때문에 그런 것 일 수도 있겠지만, 제 프로젝트의 경우 키 하나마다 각자 애니메이션이 동작하게 되어있어 캔버스를 자주 호출하는 것이 원인이 될 수도 있을 것 같습니다.

혹시 캔버스 애니메이션에 버벅임이 발생하신다면 requestAnimationFrame을 써보는 것도 좋을 것으로 생각이 됩니다. 참고한 곳은 다음 두 곳입니다.
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
https://msdn.microsoft.com/ko-kr/library/hh920765(v=vs.85).aspx
