### ISSUE TITLE
★ [공지] 두 번째 밋업 참가 신청 (2월 13일-화) 

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CampusFest/5th#14]
2월 13일(화) D2 StartupFactory에서 두 번째 밋업이 진행됩니다.
※ 두 번째 밋업에 참여를 원하시는 분은 댓글 남겨주세요!

참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.
오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!

일시 : 2월 13일(화), 오후 2시 - 7시
장소 : 강남역 메리츠 타워 16층 D2 Startup Factory [(위치보기)](https://map.naver.com/local/siteview.nhn?code=36797269)
★1층 오른쪽 출입구에서 16층 간다고 말해주시면 열어주실꺼에요!!★

오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
오후 5시 - 7시 : Tech Talk (w/ pizza party)
Tech Talk 발표를 원하시는 분들도 댓글로 알려주세요 :)
(*발표는 5~20분 정도로 희망자 수에 따라 시간은 조절될 수 있습니다.)

**Comment by bbvch13531** [comment]
안녕하세요 prefeel-lib 팀의 허경영입니다.
오늘 밋업때 여러분들하고 좀 더 친해진 것 같아 좋았습니다!!
오늘 발표를 들으면서 저도 여러분들께 뭔가 도움이 될 수 없을까 고민하다가 
@Kang-heesuk 님의 제안으로 chromium에 contribution하기를 주제로 
다음 밋업때 발표를 해보려고 합니다.

발표자료: https://www.slideshare.net/ssuser3d03b2/chromium-contributhon-87908355
그리고 오늘 얘기가 나왔던 치킨 피보나치 수는
1 1 2 3 5 8 13...의 피보나치 수열을 이용해
1인 1닭, 2인 1닭, 3인 2닭... 으로 먹는 것이 이상적이라는 유머였습니다.
 [치킨 피보나치 계산기](http://fibonachicken.herokuapp.com/#)
1인 1.618닭이라는 황금비로 수렴하네요 ㅋㅋㅋ

그럼 다음밋업때 뵙겠습니다!!

**Comment by oh3vci** [comment]
prefeel-lib 팀 2명(김대호 @oh3vci, 허경영 @bbvch13531) 참여합니다.

**Comment by Red-Portal** [comment]
mgcpp 팀 2명 김규래, 박건 참여합니다!

**Comment by wooooooong** [comment]
thstorytellingview팀 3명 모두 참여합니다.

**Comment by xxxnell** [comment]
flip팀 1명 참여합니다.

**Comment by kuj0210** [comment]
IoT Pet pet home system 팀 전원참석하겠습니다(표관련으로 일정이 꼬여서...늦게 글달아 죄송합니다)

**Comment by poirin** [comment]
MyDiary팀 2명 참여합니다

**Comment by oh3vci** [comment]
prefeel-lib 팀 이우찬 @WoochanLee 추가 참여합니다.

**Comment by Red-Portal** [comment]
mgcpp팀 2명 갑자기 각자 일이 생겨서 참여를 못할 것 같습니다. 늦게 알려드려서 정말 죄송합니다

**Comment by bbvch13531** [comment]
@Red-Portal https://github.com/D2CampusFest/5th/issues/15 여기에 다시 달아주시면 좋을 것 같아요!
이 이슈는 closed된 두번째 밋업이어서요~
