### ISSUE TITLE
★ [공지] 마지막 밋업 참가 신청 (2월 22일-목)

### ISSUE THREAD

**Issue by matianddo2** [D2CampusFest/5th#15]
2월 22일(목) D2 StartupFactory에서 세 번째 밋업(마지막 밋업)이 진행됩니다.
※ 세 번째 밋업에 참여를 원하시는 분은 댓글 남겨주세요!

참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.
오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!

일시 : 2월 22일(목), 오후 2시 - 7시
장소 : 강남역 메리츠 타워 16층 D2 Startup Factory [(위치보기)](https://map.naver.com/local/siteview.nhn?code=36797269&_ts=1518505957871)
★1층 오른쪽 출입구에서 16층 간다고 말해주시면 열어주실꺼에요!!★

오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
오후 5시 - 7시 : Tech Talk (w/ pizza party)
Tech Talk 발표를 원하시는 분들도 댓글로 알려주세요 :)
(*발표는 5~20분 정도로 희망자 수에 따라 시간은 조절될 수 있습니다.)

**Comment by KimBoWoon** [comment]
AndroidLogData팀 김보운 참가합니다!!

**Comment by Red-Portal** [comment]
mgcpp 팀 김규래, 박건 2명 참석합니다

**Comment by bbvch13531** [comment]
prefeel-lib팀 허경영 1명 참가합니다!

**Comment by so3500** [comment]
Nanum 팀 이성온, 정구범 2명 참석합니다!

**Comment by hcn1519** [comment]
THStorytellingView 팀 3명 전원 참석합니다.

**Comment by xxxnell** [comment]
flip팀 1명 참석합니다. 당일 일정때문에 좀 늦을 수도 있을 것 같습니다.

**Comment by poirin** [comment]
MyDiary팀 2명 참석합니다

**Comment by JuhoKang** [comment]
bigpicture-light 팀 2명 참석합니다.

**Comment by beta1360** [comment]
IoT-Pet-Home-System [(구)opensourceproject] 팀 2명 참석합니다.(이건희 고대석)
팀원 1명(김우진)은 올 수도 있고 못 올수도 있기 때문에 우선 보류해두겠습니다.

**Comment by ryuhangyeong** [comment]
daily-health-originer 참가합니다.

간단하게 발표하고 싶어요.

[발표자료 다운로드 링크](http://naver.me/GoaBRW7u)

**Comment by bbvch13531** [comment]
안녕하세요 이번에 개발을 완성하지 못할 것 같은 prefeel-lib팀의 허경영입니다. ㅠㅠ
최종 제출일이 얼마 안남았는데 이번 심사기준에 30점이나 포함되는

발전가능성 20 : 앞으로 오픈소스로서의 얼마나 발전가능하며, 확장(지속)가능한가
프로젝트 문서화 10 : 오픈소스로서 README, Install guide, License 등의 기초 문서가 잘 갖추어져 있는가

에 대해서 도와드리고 발표도 하려고 합니다!

2시부터 5시까지 깃헙 문서화 챙기시고 30점 채우는 부분에 관심 있으신 분들 계시면 댓글 달아주실래요??
제가 도와드릴 수 있을 것 같아요! 

다음과 같은 내용에 대해 발표하고, 도와드릴 예정입니다!
- issue, pull request template
- badge images 
- GPG key 설정
- milestone
- project boards
- webhook
- travis CI 
- commit naming /브랜치 관리전략
발표자료는 여기에서 보실 수 있습니다. [Github 문서화의 끝](https://drive.google.com/file/d/1D9TZBG0rgO7d5h8tpQm_N0tk9yRdgs2b/view)

저번 발표때 부족한 부분을 보완해서 이번엔 더 나은 발표를 해보겠습니다. 
질문은 언제나 환영이에요!

**Comment by xxxnell** [comment]
안녕하세요, 밋업때 [(아주 간단히) 스칼라로 함수형 프로그래밍하기](https://github.com/D2CampusFest/5th/files/1741436/meetup-why-scala.pdf)라는 주제로 발표하고 싶은데 괜찮을까요? 
https://www.slideshare.net/Nell4/functional-programming-in-scala-in-a-nutshell

**Comment by bbvch13531** [comment]
@xxxnell 오 함수형 프로그래밍에 관심 많습니다!! 발표자료 보니 더 기대되네요

**Comment by Kang-heesuk** [comment]
@ryuhangyeong @xxxnell 네네 두분 발표 우와아아전 좋습니다 :)

@bbvch13531 허경영님은 Tech talk 시간은 아니고 별도로 개발 시간 중에 발표와 도우미 활동을 하시는 건가요?? 원하시면 별도로 회의 실 하나 잡아드릴 수 있어요 ㅎㅎ 확인 부탁드립니다!!

**Comment by bbvch13531** [comment]
@Kang-heesuk 말씀 정말 감사합니다. 근데 몇분정도 관심있으신지 몰라서요 별도의 공간까지는 필요하지 않을것 같습니다

**Comment by Red-Portal** [comment]
아 여기다가 다시 적습니다.
mgcpp 2명 각자 급한일이 생겨서 참석이 힘들 것 같습니다.
늦게 알려드려서 죄송합니다
