### ISSUE TITLE
결승전 발표자료를 취합합니다!

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CampusFest/5th#16]
26일(월) 자정까지 발표자료를 댓글로 남겨주세요!
- 행사장에서는 참가자 노트북의 wifi 사용이 불가합니다. (인터넷 가능한 공용 노트북 Mac, Windows 로 발표진행)

1. 영상을 준비하신 경우 URL도 함께 남겨주세요. (현장의 네트워크 문제로 인해 데모가 필요한 경우 미리 영상으로 준비하시는 것을 추천드립니다.)
2. 폰트 깨짐 등을 방지 하기 위해 발표자료는 pdf 형식으로 제출하는 것을 추천합니다. 
(애니메이션 등이 필요한 경우에는 다른 형식으로 업로드 하셔도 무방합니다.)

파일용량 등의 제한이 있는 경우에는 slideshare 등의 url을 공유해주시거나 naver_d2@naver.com 으로 전달부탁드립니다.

**Comment by Red-Portal** [comment]
(수정) 확인후 다시 제출하겠습니다 ㅠ

**Comment by Kang-heesuk** [comment]
@Red-Portal 두 번째 페이지에 메인테이너 정보가 잘 못 표기된거 같아요 :) 확인 부탁드립니다~

**Comment by Red-Portal** [comment]
mgcpp 팀 제출합니다!

[mgcpp.pdf](https://github.com/D2CampusFest/5th/files/1757739/mgcpp.pdf)

**Comment by so3500** [comment]
Nanum 팀 제출합니다!

[Nanum.pdf](https://github.com/D2CampusFest/5th/files/1758708/Nanum.pdf)
[Demo](https://youtu.be/jdjNf8WhoN0)

**Comment by ryuhangyeong** [comment]
daily-helath-originer 팀 제출합니다!

[daily-health-originer.pdf](https://github.com/D2CampusFest/5th/files/1758203/daily-health-originer.pdf)

**Comment by ryuhangyeong** [comment]
daily-health-originer 팀 제출합니다!
[daily-health-originer.pdf](https://github.com/D2CampusFest/5th/files/1758210/daily-health-originer.pdf)

**Comment by rouismia** [comment]
LaunchPAD_JS 팀 제출합니다. 시연 영상은 메일로 보냈습니다.
[LaunchPAD_JS.pdf](https://drive.google.com/file/d/1YvizIYsr3u2kVWcqggtbgBQP1vn7QD4e/view?usp=sharing)
[LaunchPAD_JS_Animation.pptx](https://drive.google.com/open?id=10vYA8JDXmekANfwbfhpdz4pri6KAOQHK)

**Comment by JuhoKang** [comment]
big-picture-light 팀 제출합니다.
[big-picture-light.pdf](https://github.com/D2CampusFest/5th/files/1758531/big-picture-light.pdf)
demo https://youtu.be/2cY8FLdUUA0
pdf 버전으로 제출하고 발표때 사용할 ppt는 메일로 보내드립니다 😃

**Comment by poirin** [comment]
MyDiary 팀 제출합니다
[MyDiary.pdf](https://github.com/D2CampusFest/5th/files/1758577/MyDiary.pdf)

**Comment by beta1360** [comment]
IoT-Pet-Home-System 팀 제출합니다!(23:12부로 수정했습니다)
[IoT_Pet_House_System.pdf](https://github.com/D2CampusFest/5th/files/1758893/IoT_Pet_House_System.pdf)

**Comment by HyunmoAhn** [comment]
oh-my-desk 팀 발표자료 제출합니다.
[oh-my-desk.pdf](https://github.com/D2CampusFest/5th/files/1758854/oh-my-desk.ppt.pdf)

**Comment by KimBoWoon** [comment]
Android-Log-Data 발표자료 제출합니다.
[Android-Log-Data.pdf](https://github.com/D2CampusFest/5th/files/1758875/Android-Log-Data.pdf)

**Comment by xxxnell** [comment]
발표자료와 데모를 메일로 제출했습니다. 감사합니다.

**Comment by wooooooong** [comment]
[THStorytellingView.pdf](https://github.com/D2CampusFest/5th/files/1758927/THStorytellingView.pdf)
발표자료 제출합니다.

**Comment by SuekyeongNam** [comment]
Mosaicer 파일 용량이 커 메일로 자료 보내드립니다. 감사합니다.

**Comment by bbvch13531** [comment]
발표자료 메일로 제출했습니다!

**Comment by hwonyo** [comment]
[naver_talk_sdk.pdf](https://github.com/D2CampusFest/5th/files/1759083/naver_talk_sdk.pdf)

**Comment by byeolbit** [comment]
[Dr.Jekyll-D2CampusFest.pdf](https://github.com/D2CampusFest/5th/files/1760180/Dr.Jekyll-D2CampusFest.pdf)

**Comment by Kang-heesuk** [comment]
오늘의 발표순서입니다!

1. Mosaicer
2. Oh-my-desk
3. MyDiary
4. Naver_talk_sdk
5. Android Log Data
6. THStoryTelling View
7. Big picture-light
8. Mgcpp
9. Dr.Jekyll
10. LaunchPAD_JS
11. Flip
12. Nanum
13. Daily-health-originer
14. Prefeel-lib
15. IoT-Pet-House(구.opensourceproject)

**Comment by Kang-heesuk** [comment]
오늘 다들 정말 멋졌습니다 :) 꺄오
