### ISSUE TITLE
[TileImageTeamiOS/UIScrollView_marker] 컨텐츠 서버 연동

### ISSUE THREAD

**Issue by grohong** [D2CampusFest/5th#5]
[컨텐츠 서버 연동](https://github.com/TileImageTeamiOS/UIScrollView_marker/issues/6)
-> 서버의 컨텐츠 연동에 대해 의논해 보고 싶습니다!

**Comment by hcn1519** [comment]
THTiledImageView 버전 [0.3](https://github.com/TileImageTeamiOS/THTiledImageView/tree/0.3)부터 서버로부터 이미지를 비동기로 받아와 업데이트하는 기능이 구현되었습니다.

기능 동작 순서는 다음과 같습니다.
1. 작은 사이즈의 설정된 배경 이미지를 로딩한다. 배경 이미지는 사이즈가 100kb 내외이기 때문에 빠르게 로딩됩니다.
2. 화면에 나타나는 ScrollView의 줌 레벨과 필요한 타일 이미지 좌표를 계산한다.
3. 업데이트가 필요한 부분에 캐싱되어 있는 이미지가 있다면 이를 곧바로 로딩한다. 만약 없으면 서버로부터 필요한 부분에 대해 background Thread에서 이미지 다운로드를 수행한다.
4. 메인 Thread에서 다운로드 및 캐싱이 완료된 이미지에 해당하는 타일이미지를 전체 이미지뷰에 맞춰서 로딩한다.

혹시 시간이 가능하다면 동작원리에 대해 정리한 글을 올릴 수 있도록 하겠습니다.
