### ISSUE TITLE
[Mosaicer] 알림 처리

### ISSUE THREAD

**Issue by seongahjo** [D2CampusFest/5th#7]
Mosaicer에서 작업이 완료되면 알림이 뜹니다.

애플리케이션 특성상 소요되는 시간이 긴 작업들이 있습니다.

이런경우 작업이 완료되기 전에  AJAX 요청이 끝나 사용자가 제때 알람을 받지 못하는 경우가 있습니다.

임시적으로 서버 설정을 변경하여 AJAX 요청 시간을 늘린다면 문제를 해결할 수 있으나

이 방법은 요청에 대한 오버헤드가 발생합니다.

현재 생각하고 있는 방법은 HTTP/2.0에서 지원하는 Server Push를 사용하여

해당 작업이 완료되면 서버에서 알림을 주는 방법을 생각하고 있습니다.

다만 이 방법의 경우 HTTP/2을 지원하지 않는 브라우저를 사용하는 사용자에게 적용할 수 없습니다.

조언 부탁드립니다.

**Comment by rouismia** [comment]
비동기 작업의 완료를 push하는 것에 대한 이야기인 것 같은데,
저는 클라이언트에서 해결하는 방법과 서버단에서 알림을 주는 방법을 사용하였습니다.
클라이언트의 경우에는, await이나 비동기 함수 안에서 작업 완료 알림을 주는 방법을 사용하였고
서버단에서는 작업 완료시 done 메세지를 보내는 것으로 해결을 하였습니다.
물론 timeout이 발생할 경우에는 정상적으로 동작하지 않는다는 문제점이 존재하지만,
이 방법을 사용하기 전 보다는 문제가 발생하는 횟수가 줄어들게 되었습니다.

**Comment by seongahjo** [comment]
@rouismia 답변 감사합니다.
제가 설명이 약간 부족했던 것 같은데 저희 애플리케이션에에서 늦으면 1시간이 넘는 작업이 있습니다.
물론 시간이 얼마 안걸리는 작업의 경우에는 말씀하신 것처럼 문제가 없지만
이런 특수한 경우에 알림이 완료이전에 timeout일 때 나와서 문제가 되고 있습니다.
그리고 질문이 있습니다. 저는 일반적으로 말씀하신 방법으로 처리하는 걸로 알고 있는데
이전에 쓰셨던 방법은 어떤 방법인가요? 
여러 가지 방법을 알면 이 문제를 해결할 수 있을 것 같아 질문 드립니다.

**Comment by rouismia** [comment]
@seongahjo 코맨트를 읽어보니 서버단에서 수행하는 작업의 양이 큰 것 같습니다. 다른 프로젝트를 수행했을 때, 작업 시간이 긴 비동기 통신을 위해 코멧을 사용했었는데, 혹시 적용중이신지 잘 모르겠습니다. 롱 폴링을 이용해서 서버단의 데이터 변화가 생기면 클라이언트로 전송하는 방식으로 해결했었는데 도움이 될 만한 링크를 하나 달아드리겠습니다.
https://vnthf.github.io/blog/Front-What_is_comet/

**Comment by seongahjo** [comment]
@rouismia 옙. 자세한 답변 감사합니다.
한 번 다양하게 시도해봐야겠네요.
