### ISSUE TITLE
[daily-health-originer] 채팅 기능 구현시 방(Room) 정보를 저장할 매체 선정에 관하여

### ISSUE THREAD

**Issue by ryuhangyeong** [D2CampusFest/5th#8]
# 이슈
> 채팅 기능 구현시 방(Room) 정보를 저장할 매체 선정에 관하여

## 이슈 URL
<https://github.com/ryuhangyeong/daily-health-originer/issues/9/>

## 개요
Daily 는 사용자들간의 원활한 소통을 위하여, 자체적으로 커뮤니티 페이지와 채팅 기능을 구현하고자 합니다. 초기버전에서 public 채팅 기능을 구현하였고, 최종버전에서는 public 채팅과 private 채팅, room 채팅등 다양한 형태의 채팅 기능을 제공하고자 합니다. 

## 문제점
public 채팅의 경우에는 메시징 정보를 데이터베이스에 저장한 이후에 클라이언트에서 Socketio 이벤트 요청을 통하여 불러와서 화면에 표시하였지만, private 채팅과 room 채팅을 제공하면서 방(room) 정보를 어디에 저장하는 것이 좋을까? 라는 의문이 들었습니다.

## 방(Room) 정보를 저장하기 위한 여러가지 매체에 대하여
1. 서버내 배열
사용자가 방에 접속하거나 1:1 대화 사용시, 배열에 room정보를 추가합니다. 이 경우, 서버가 예상치 못한 이유로 재시작하는 경우, 방 정보(Room)가 초기화되는 문제점이 생깁니다.

2. 데이터베이스(MongoDB)
사용자가 방에 접속하거나 1:1 대화 사용시, 데이터베이스에 room정보를 추가합니다. 이 경우, 빈번하게 데이터베이스를 조회하게 된다는 문제점이 생깁니다.

## 중간 결론
여러 가지를 고려해볼때 가장 좋은 방법은 역시, **데이터베이스**에 저장하는 것이 가장 좋은 방법이겠지만, 더 좋은 방법이 있다면 알려주세요!

**Comment by seongahjo** [comment]
room 정보가 정확히 뭔지 모르겠지만 단순히 방만 나타내는 정보라면 

Redis, Memcached같은 인 메모리 데이터베이스를 쓰시는게 어떨까 싶습니다.

**Comment by seongahjo** [comment]
room 정보가 정확히 뭔지 모르겠지만 단순히 방만 나타내는 정보라면

Redis, Memcached같은 인 메모리 스토리지를 쓰시는게 어떨까 싶습니다.

**Comment by ryuhangyeong** [comment]
@seongahjo 의견 감사합니다. 이슈에서 말하는 **Room 정보** 는 Socketio의 Id 값이나 Room 가입을 위한 중복되지 않는 id 값을 의미합니다. 알려주신 **redis**와 **memcached**에 대해서 알아보겠습니다.
